import { useMemo, useState } from "react";
import PageFrame from "../components/shell/PageFrame";
import Panel from "../components/ui/Panel";
import { Badge, Dot } from "../components/ui/Badge";
import { useTerminal } from "../terminal-context";
import { formatLogTime } from "../lib/format";
import type { ActivityType } from "../types/trading";

const TYPES: (ActivityType | "ALL")[] = [
  "ALL",
  "ERROR",
  "WARNING",
  "TRADE",
  "SUCCESS",
  "SYSTEM",
  "INFO",
];

const TONE: Record<ActivityType, "ok" | "bad" | "warn" | "info" | "muted"> = {
  SUCCESS: "ok",
  ERROR: "bad",
  WARNING: "warn",
  TRADE: "info",
  SYSTEM: "muted",
  INFO: "muted",
};

/**
 * Terminal-style event log.
 *
 * Important limitation, stated in the UI rather than hidden: these events are
 * generated by this browser tab (API transitions, operator actions), not read
 * from a server-side event store. They do not survive a refresh and they do not
 * include events that occurred while the dashboard was closed. A persisted feed
 * requires GET /api/events — see docs/MAYHEM_UI_ASSESSMENT.md §5.
 */
export default function ActivityPage() {
  const { activity } = useTerminal();
  const [type, setType] = useState<ActivityType | "ALL">("ALL");
  const [query, setQuery] = useState("");

  const rows = useMemo(() => {
    const q = query.trim().toLowerCase();
    return activity.filter((e) => {
      if (type !== "ALL" && e.type !== type) return false;
      if (q && !e.message.toLowerCase().includes(q)) return false;
      return true;
    });
  }, [activity, type, query]);

  function exportJson() {
    const blob = new Blob([JSON.stringify(rows, null, 2)], {
      type: "application/json",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `mayhem-activity-${new Date().toISOString()}.json`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <PageFrame
      meta={`${rows.length} of ${activity.length} events`}
      actions={
        <>
          <select
            className="mh-select"
            style={{ width: 130 }}
            value={type}
            onChange={(e) => setType(e.target.value as ActivityType | "ALL")}
            aria-label="Severity filter"
          >
            {TYPES.map((t) => (
              <option key={t} value={t}>
                {t === "ALL" ? "All severities" : t}
              </option>
            ))}
          </select>
          <input
            className="mh-input"
            style={{ width: 240 }}
            placeholder="search events"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            aria-label="Search events"
          />
          <button type="button" className="mh-btn" onClick={exportJson} disabled={rows.length === 0}>
            Export JSON
          </button>
        </>
      }
    >
      <div style={{ display: "grid", gap: 8, minHeight: 0 }}>
        <div className="mh-banner" data-tone="warn">
          <span>
            <strong>Session-scoped log.</strong> These events are produced by
            this browser session and are lost on refresh. The API has no
            persisted event store, so anything that happened while the dashboard
            was closed is not shown here.
            <span className="mh-mono"> requires: GET /api/events</span>
          </span>
        </div>

        <Panel title="Event Log" meta={<Badge tone="warn">session only</Badge>}>
          {rows.length === 0 ? (
            <div className="mh-empty">
              <span className="mh-empty__title">No matching events</span>
            </div>
          ) : (
            <table className="mh-table">
              <thead>
                <tr>
                  <th style={{ width: 110 }}>Timestamp</th>
                  <th style={{ width: 100 }}>Severity</th>
                  <th>Event</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((e) => (
                  <tr key={e.id}>
                    <td className="mh-mono">{formatLogTime(e.timestamp)}</td>
                    <td>
                      <span className="mh-row" style={{ gap: 6 }}>
                        <Dot tone={TONE[e.type]} />
                        <span className="mh-mono">{e.type}</span>
                      </span>
                    </td>
                    <td>{e.message}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </Panel>
      </div>
    </PageFrame>
  );
}
